version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run: docker build -t registry.digitalocean.com/roadmap-ai-container-registry/currency-converter:latest .
